"""
LISTAS EM PYTHON, TIPO DE LIST - MUTÁVEL
SUPORTA VÁRIOS VALORES DE QUALQUER TIPO
CONHECIMENTOS REUTILZIÁVEIS - INDICES E FATIAMENTO
MÉTODOS UTÉIS APPEND, ISERT, POP, DEL, CLEAR, EXENTED, MAIS
"""

#       01234
#      -54321

string = 'ABCDE' #5 CARACTERES